#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDC_COMBO1                              106
#define IDC_BUTTON1                             107
#define IDC_SINK                                109
#define IDC_TAB1                                111
#define IDM_LAYERTOOL                           112
#define IDC_BUTTON2                             113
#define IDM_LOADSCRIPT                          114
#define IDM_LOADSOUND                           115
#define IDM_LOADMOVIE                           116
#define IDC_EDIT1                               1001
#define IDC_EDIT2                               1002
#define IDC_EDIT3                               1003
#define IDC_EDIT4                               1004
#define IDC_EDIT5                               1005
#define IDC_EDIT6                               1006
#define IDC_EDIT7                               1007
#define IDC_EDIT8                               1008
#define IDC_EDIT9                               1009
#define IDC_EDIT10                              1010
#define IDC_EDIT11                              1011
#define IDC_EDIT12                              1012
#define IDC_EDIT13                              1013
#define IDC_EDIT14                              1014
#define IDC_EDIT15                              1015
#define IDC_EDIT16                              1016
#define IDC_SPIN1                               2001
#define IDC_SPIN2                               2002
#define IDC_SPIN3                               2003
#define IDC_SPIN4                               2004
#define IDC_SPIN5                               2005
#define IDC_SPIN6                               2006
#define IDC_SPIN7                               2007
#define IDC_SPIN8                               2008
#define IDC_SPIN9                               2009
#define IDC_SPIN10                              2010
#define IDC_SPIN11                              2011
#define IDC_SPIN12                              2012
#define IDC_SPIN13                              2013
#define IDC_SPIN14                              2014
#define IDC_SPIN15                              2015
#define IDC_SPIN16                              2016
#define IDC_SLIDER1                             3001
#define IDC_SLIDER2                             3002
#define IDC_SLIDER3                             3003
#define IDC_SLIDER4                             3004
